package com.sz_device.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sz_device.Bean.FingerprintUser;
import com.sz_device.Bean.ReUploadBean;

import com.sz_device.greendao.FingerprintUserDao;
import com.sz_device.greendao.ReUploadBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerprintUserDaoConfig;
    private final DaoConfig reUploadBeanDaoConfig;

    private final FingerprintUserDao fingerprintUserDao;
    private final ReUploadBeanDao reUploadBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerprintUserDaoConfig = daoConfigMap.get(FingerprintUserDao.class).clone();
        fingerprintUserDaoConfig.initIdentityScope(type);

        reUploadBeanDaoConfig = daoConfigMap.get(ReUploadBeanDao.class).clone();
        reUploadBeanDaoConfig.initIdentityScope(type);

        fingerprintUserDao = new FingerprintUserDao(fingerprintUserDaoConfig, this);
        reUploadBeanDao = new ReUploadBeanDao(reUploadBeanDaoConfig, this);

        registerDao(FingerprintUser.class, fingerprintUserDao);
        registerDao(ReUploadBean.class, reUploadBeanDao);
    }
    
    public void clear() {
        fingerprintUserDaoConfig.clearIdentityScope();
        reUploadBeanDaoConfig.clearIdentityScope();
    }

    public FingerprintUserDao getFingerprintUserDao() {
        return fingerprintUserDao;
    }

    public ReUploadBeanDao getReUploadBeanDao() {
        return reUploadBeanDao;
    }

}
